### ISSUE TITLE
Other view fading out ?

### ISSUE THREAD

**Issue by cnshu** [courtneypattison/react-native-fade-in-out#31] opened 2022-01-01 08:15 UTC
when I use FadeInOut with one view my all the views fadeout

**Comment by courtneypattison** [comment] 2022-01-01 13:17
@cnshu Hmm, only the children of FadeInOut should fade. Could you provide some sample code or a snack so I can troubleshoot for you? If you look at the source, you can try to implement the fading yourself, just using the props you need.

**Comment by blindgaenger** [comment] 2022-02-25 21:36
Hi! I think `useRef` has the described effect since the reference is used across all instances of the component.

https://github.com/courtneypattison/react-native-fade-in-out/blob/master/src/index.tsx#L26

You may reproduce the problem with a very long duration while toggling the values from other instances. Should easily be fixed with a `useState` instead.

**Comment by courtneypattison** [comment] 2022-03-07 19:19
@blindgaenger Thank you so much for your help! Unfortunately, I still cannot reproduce the problem with the steps you provided. Could you pretty please make a snack showing the issue? Something like [this snack](https://snack.expo.dev/@courtneypattison/anxious-edamame). I'd really like to resolve this issue. Admittedly, I don't have a lot of experience with react native, but from what [I've read](https://stackoverflow.com/questions/59589384/react-useref-or-module-scope-to-store-ui-independent-state#:~:text=The%20difference%20between%20useRef%20and%20a%20module%2Dscope%20variable&text=useRef%20%3A%20mutable%20data%20that's%20also,it's%20completely%20outside%20of%20React.) `useRef()` is tied to the component instance, so should not affect other instances of the component. I'm hesitant to switch to `useState()` because it will cause additional rerenders. Also, all of the [example animations in the react native docs](https://reactnative.dev/docs/animations) use `useRef()`.

Thank you again!

**Comment by blindgaenger** [comment] 2022-03-08 13:00
I tried it briefly, but I could not reproduce the problem in the snack.

https://snack.expo.dev/@blindgaenger/anxious-edamame

I'm afraid I don't remember what the components looked like at the time, as I was just trying out your library. I agree with you that `useRef` is the right solution to avoid wasted renders.

All the best!

**Comment by courtneypattison** [comment] 2022-03-08 18:20
@blindgaenger Thank you so much for trying to reproduce the problem!

**Closed** 2022-06-05 21:48 UTC
